[package]
name = "packet_generator"
version = "0.2.2"
authors = ["L3nn0x <dragon83.super@gmail.com>"]

[dependencies]
schema = { path = "../schema" }
failure = "0.1"
heck = "0.5"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
simple_logger = "5.0"
